### ISSUE TITLE
Confusion about NOT_FOUND_EXTERNAL and NOT_FOUND_INTERNAL IP types

### ISSUE THREAD

**Issue by J-lena** [Kindling-project/kindling#137]
In the topology view, I found IP node tags with two types: NOT_FOUND_EXTERNAL and NOT_FOUND_INTERNAL.  What do those types stand for and why Kindling provide two different IP types.

![image](https://user-images.githubusercontent.com/97420104/159645720-7a9ff5c5-655f-4486-adb4-3ee238adbd2f.png)

**Comment by dxsup** [comment]
These two values are composed of two parts.
#### NOT_FOUND
`NOT_FOUND` means the IP is neither a Pod's one nor a Service's one in the Kubernetes cluster. The IP could belong to a host or an external service.

#### INTERNAL and EXTERNAL
`INTERNAL` means the IP belongs to a Node in the cluster or a host on which the kindling agent is running. `EXTERNAL` is set for other cases if the IP is `NOT_FOUND`.

I will add these descriptions to the metric documentation.
