### ISSUE TITLE
Hoping kindling will support dubbo protocol

### ISSUE THREAD

**Issue by J-lena** [Kindling-project/kindling#175]
Now Kindling supports HTTP protocol already, but my microservices are under Dubbo protocol, I also want to know the performance  of Dubbo api. Can Kindling support Dubbo protocol?

**Comment by dxsup** [comment]
The protocol `dubbo2` is supported after merging #184. See metrics [document](https://github.com/Kindling-project/kindling/blob/main/docs/prometheus_metrics.md) for more information.
