### ISSUE TITLE
How to get the image

### ISSUE THREAD

**Issue by trestea** [Kindling-project/kindling#182]
After which step can I see the image
<img width="858" alt="image" src="https://user-images.githubusercontent.com/17846940/163670881-4e833d7d-a780-4df1-ada4-62d6523a5c1d.png">
Of which 16 and 18 report errors

**Comment by sanyangji** [comment]
Once you run `bazel build -s --config=clang src/probe:push_image` or `bazel build -s --config=clang src/probe:push_image_localdriver` successfully, you will have the image. You can see the image in the docker registry(configured in kindling/probe/src/probe/BUILD.bazel), after you run `./bazel-bin/src/probe/push_image` or `./bazel-bin/src/probe/push_image_localdriver` correspondingly.
You can add more information about the errors.

**Comment by dxsup** [comment]
Any updates?

**Comment by dxsup** [comment]
Closed since no reponse. If you have any other questions on this issue, please feel free to reopen it.
