### ISSUE TITLE
HTTP request is recognized as UNSUPPORT

### ISSUE THREAD

**Issue by hocktea214** [Kindling-project/kindling#188]
**Describe the bug**
A HTTP application is benched with wrk, we expect the protocol is HTTP only. However, there are some UNSUPPORT datas.

**How to reproduce?**
Start test-netserver
./wrk -t5 -c20 -d60 http://xxx:9000/test?sleep=1

**What did you expect to see?**
All datas are recognized as HTTP

**What did you see instead?**
Some datas are recognized as UNSUPPORT

**Screenshots**
![image](https://user-images.githubusercontent.com/7486614/164199635-ffd081fd-c03c-4445-9ce8-f773efda5123.png)

**Comment by dxsup** [comment]
Closed by #189
