### ISSUE TITLE
No more kindling events can be sent after the convert list is full

### ISSUE THREAD

**Issue by sanyangji** [Kindling-project/kindling#197]
**Describe the bug**
No more kindling events can be sent after the convert list exceeds the max size. The process of convert stopped when list is full because it has no try to swap convert list and send list.

**How to reproduce?**
1. set list_max_size.
2. give some pressure to exceed the max size.
3. get the convert part stopped which causes no more kindling events can be sent.

**What did you expect to see?**
kindling events can be sent correctly.

**Comment by dxsup** [comment]
Closed by #200
