### ISSUE TITLE
Collector needs more valuable logs

### ISSUE THREAD

**Issue by jundizhou** [Kindling-project/kindling#39]
**Is your feature request related to a problem? Please describe.**
There are too few useful logs in collector, and almost no logs are typed
![image](https://user-images.githubusercontent.com/92794317/154058098-5462ff16-2761-4516-9562-a9b7d5a3fa8a.png)

**Describe alternatives you've considered**
add some logs.For example,count the number of traces.

**Comment by dxsup** [comment]
We have added a couple of telemetry metrics. The followings are part of them.
```
kindling_telemetry_udsreceiver_events_total
kindling_telemetry_netanalyer_messagepair_size
kindling_telemetry_netanalyer_parsedrequest_total
kindling_telemetry_conntracker_cache_size
kindling_telemetry_conntracker_cache_max_size
kindling_telemetry_conntracker_operation_times_total
kindling_telemetry_otelexporter_gaugegroups_received_total
kindling_telemetry_otelexporter_cardinality_size
```

These metrics are printed on the stdout by default and users could export these metrics via Prometheus or Opentelemetry-protocol by modifying the following configuration.
https://github.com/Kindling-project/kindling/blob/b9ed64f761bbc8d8883d910dd69530a29cdea2a9/deploy/kindling-collector-config.yml#L132-L143

Besides, we have improved the log details when an error happens, which could tell when and why the collector can't work as expected. If anyone finds any part of logs or telemetry is necessary to be improved further, please feel free to open an issue, and we will discuss and improve it.
