### ISSUE TITLE
What are the minimal set of Linux capabilities the agent requests?

### ISSUE THREAD

**Issue by dxsup** [Kindling-project/kindling#54]
There are some security concerns regarding why the agent must use root privileges. It's typical that the users only want to give the minimal set of privileges if possible. We need to explain which privileges are necessary and why. Then we could set Linux capabilities to restrict the range of privileges.

https://github.com/Kindling-project/kindling/blob/fe3467ba0192895762ec2d9eeb89c5bd712de160/deploy/kindling-deploy.yml#L56

https://github.com/Kindling-project/kindling/blob/fe3467ba0192895762ec2d9eeb89c5bd712de160/deploy/kindling-deploy.yml#L102

**Comment by sanyangji** [comment]
<p cid="n922" mdtype="paragraph" class="md-end-block md-p md-focus" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; text-indent: 2em; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box; text-indent: 0px;">I list the Linux capabilities  for falcolib as below.</span></p><figure class="md-table-fig" cid="n852" mdtype="table" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);">

  | eBPF
-- | --
setrlimit | SYS_RESOURCE
syscall bpf | SYS_ADMIN or SYS_BPF (Linux kernel 5.8+)
syscall perf_event_open | SYS_ADMIN or SYS_PERFMON (Linux kernel 5.8+)
/host/proc | root privilege, or using pid=host and set SYSDIG_HOST_ROOT=""

</figure><p cid="n920" mdtype="paragraph" class="md-end-block md-p" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; text-indent: 2em; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box; text-indent: 0px;">For falcolib using eBPF，we can run with capabilities SYS_RESOURCE, SYS_ADMIN and pid=host.</span></p>
<figure class="md-table-fig" cid="n897" mdtype="table" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);">

  | kernel
-- | --
insmod | SYS_MODULE
/host/dev | root privilege
/host/proc | root privilege

</figure><p cid="n921" mdtype="paragraph" class="md-end-block md-p md-focus" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; text-indent: 2em; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box; text-indent: 0px;">For falcolib using kernel module, we must set privileged=true.</span></p>

**Comment by dxsup** [comment]
Since we have reimplemented the conntracker module, the collector requires `privileged` now. The reason is it has to read the `net` namespace of all processes on the host to get all conntrack tables.
