### ISSUE TITLE
Miss syscall events for network analysis

### ISSUE THREAD

**Issue by sanyangji** [Kindling-project/kindling#73]
**Describe the bug**
Miss syscall events writev, readv, pwritev, preadv, pwrite, pread, which may be used for network analysis.

**What did you expect to see?**
Please subscribe these syscall_exit events in kindling-collector config. However, I haven't meet the last four yet, which can be subscribed later depending on the need.

**Comment by dxsup** [comment]
I'll update the configuration file later.
