### ISSUE TITLE
Failed to compile the agent-libs when the kernel version is below 3.10.0-693

### ISSUE THREAD

**Issue by dxsup** [Kindling-project/kindling#81]
**Describe the bug**
Failed to compile the agent-libs when the kernel version is below 3.10.0-693. There is an error complained about.

**How to reproduce?**
Just compile the agent-libs repository following the instructions at [Installation](https://github.com/Kindling-project/kindling/blob/main/installation/Installation.md) on the kernel version of 3.10.0-514 or below.

**Logs**
```log
Compile probe for 3.10.0-514.el7.x86_64
make -C /usr/src/kernels/3.10.0-514.el7.x86_64/ M=/source/driver modules
make[1]: Entering directory '/host/usr/src/kernels/3.10.0-514.el7.x86_64'
  CC [M]  /source/driver/main.o
In file included from include/linux/compiler.h:54,
                 from include/linux/kprobes.h:32,
                 from /source/driver/main.c:13:
include/linux/compiler-gcc.h:106:1: fatal error: linux/compiler-gcc8.h: No such file or directory
 #include gcc_header(__GNUC__)
 ^~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:342: /source/driver/main.o] Error 1
make[1]: *** [Makefile:1300: _module_/source/driver] Error 2
make[1]: Leaving directory '/host/usr/src/kernels/3.10.0-514.el7.x86_64'
make: *** [Makefile:17: all] Error 2
mv: cannot stat 'kindling-falcolib-probe.ko': No such file or directory
make -C /usr/src/kernels/3.10.0-514.el7.x86_64/ M=/source/driver clean
make[1]: Entering directory '/host/usr/src/kernels/3.10.0-514.el7.x86_64'
  CLEAN   /source/driver/.tmp_versions
make[1]: Leaving directory '/host/usr/src/kernels/3.10.0-514.el7.x86_64'
make -C /usr/src/kernels/3.10.0-514.el7.x86_64/ M=$PWD
make[1]: Entering directory '/host/usr/src/kernels/3.10.0-514.el7.x86_64'
clang -I./arch/x86/include -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -in
clude ./include/linux/kconfig.h \
```
**Environment (please complete the following information)**
- Kindlinng-falcon-lib version: Based on the latest codes on the branch of kindling-dev. The commit is 8c130f7c4326398372661c0148b5bba5a1a2e9d8.
- Node Kernel version: 3.10.0-514.el7.x86_64 or below
- Node OS version: CentOS7

**Additional context**
By the way, 3.10.0-693 is ok.

**Comment by sanyangji** [comment]
Kernel versions older than 3.10.0-514.el7.x86_64 have not been supported by the container images yet. The container use llvm-toolset-7.0 and devtoolset-8 to compile probes.
From the error message, we can get that the toolset used in the container (gcc8) is too new for older versions, you can build by old gcc temporarily. I will follow to fix it.

**Comment by jundizhou** [comment]
We used gcc4 9 to compile the lower version kernel
