### ISSUE TITLE
Change the repository of the bpf-compiler image 

### ISSUE THREAD

**Issue by sugary199** [Kindling-project/kindling#85]
**Describe the bug**
content "registry.us-west-1.aliyuncs.com/arms-docker-repo/bpf-compiler:kindling-without-extra" in run_docker.sh is not updated synchronously
Replace this image with ”kindlingproject/kindling-compiler“

**Comment by dxsup** [comment]
Could you spare a little time to finish this change? This would be a nice start for becoming a contributor.

**Comment by dxsup** [comment]
Closed via #89
